### PR TITLE
Fix: In-between selections not selecting

### PR DESCRIPTION
**Pull request by Mr-Badger**
8bnsn70U40

Also fixes issue when select next occurrence wraps.

### CODE REVIEW

**Comment by Mr-Badger** [comment]
Alright, I wanted to add some extra information about this PR.
There are two ways to tackle this issue, that is in-between selections. 
This one is what I'll call inward selection, that is, if selections inside the currently select selections exists then they're selected first.
The other type is outward selection, which was the previous implementation(except it never found the ones that where in-between), that selects next selection below the last selection(or previous).

I personally think inwards selection is the more logical implementation, for example if you started selecting but wanted to select case insensitive, then you only need to toggle it on and select those in-between, which would not be possible with outward selection(except you want to select all occurrences).

We could maybe add it as a toggle option.

**Comment by Mr-Badger** [comment]
Also just a side note, I checked how Sublime and VSCode does this
Sublime only has select next occurence(not previous) and does outward selection and reverse in-between selection for some reason.
VSCode handles in-between selections pretty poorly and in some cases stops selecting. The next selection is determined by the last selected selection and does ether in-between or outside selection depending where the 'main' cursor is located, but not both.

**Comment by Mr-Badger** [comment]
Added option to swap between the inward and outward selection, made inward selection the default.

**Comment by 2mas** [comment]
Cool feature, never tought about this. However, I think this behaviour might surprise users as sublime/code doesnt do this. Atleast for myself I'm expecting the search for the next occurrence to begin from the latest added cursor. This would make it impossible to use the Skip occurrence command. What do you think about implementing this but switching the default setting?

**Comment by Mr-Badger** [comment]
Yeah, I never use Skip Occurrence so I didn't do any tests with it. I changed the default to outward, think that's enough for now?

**Comment by 2mas** [comment]
I think so, merging this, gj!

**Pull request merged**
